update the entrypoint script and use NODE_EXTRA_CA_CERTS if provided
openziti/ziti-browzer-bootstrapper pull request #273
Opened 2024-06-12 20:08 UTC by dovholuknf

2024-06-12 21:38 UTC, rentallect requested changes

2024-06-12 21:38 UTC, rentallect commented on index.js
> +	const extraCaCertsPath = process.env.NODE_EXTRA_CA_CERTS;
pls change to `env('NODE_EXTRA_CA_CERTS')`

2024-06-12 21:39 UTC, dovholuknf commented on index.js
> +	}
it's set in the entrypoint script now. if `NODE_EXTRA_CA_CERTS` isn't supplied, it'll get defaulted to `node_modules/node_extra_ca_certs_mozilla_bundle/ca_bundle/ca_intermediate_root_bundle.pem`

2024-06-12 21:41 UTC, dovholuknf commented on index.js
> +	const extraCaCertsPath = process.env.NODE_EXTRA_CA_CERTS;
all set

2024-06-13 01:04 UTC, dovholuknf commented
> You can add the default value for the `NODE_EXTRA_CA_CERTS` var in `env.js` near line `52`. Doing so is tidy'er than hacking on the docker entrypoint file, and will also be applicable to non-docker bootstrapper start up's.

Ok, I'll change it... Just curious, are you sure it's necessary still? I thought it was only used because the trust store in the alpine image didn't contain a fully up-to-date set of certs?

2024-06-13 17:31 UTC, rentallect requested changes

2024-06-13 17:31 UTC, rentallect commented on index.js
> +var nconf       = require('nconf');
this is unnecessary.

2024-06-13 17:31 UTC, rentallect commented on index.js
> +    const extraCaCertsPath = nconf.get('NODE_EXTRA_CA_CERTS');
this should be `env('NODE_EXTRA_CA_CERTS')`

2024-06-13 18:59 UTC, rentallect approved these changes

2024-06-13 19:00 UTC, merged